karhabty_astuce:
    resource: "@KarhabtyAstuceBundle/Resources/config/routing.yml"


karhabty_events:
    resource: "@KarhabtyEventsBundle/Resources/config/routing.yml"

karhabty_admin:
    resource: "@KarhabtyAdminBundle/Resources/config/routing.yml"
    prefix:   /

karhabty_bank:
    resource: "@KarhabtyBankBundle/Resources/config/routing.yml"
    prefix:   /

karhabty_paiement:
    resource: "@KarhabtyPaiementBundle/Resources/config/routing.yml"
    prefix:   /

karhabty_annonce:
    resource: "@KarhabtyAnnonceBundle/Resources/config/routing.yml"
    prefix:   /annonce

Voiture:
    resource: "@KarhabtyCalendarBundle/Resources/config/routing.yml"
    prefix:   /voiture


karhabty_map:
    resource: "@KarhabtyMapBundle/Resources/config/routing.yml"
    prefix:   /

karhabty_offre:
    resource: "@KarhabtyOffreBundle/Resources/config/routing.yml"

karhabty_future_conducteur_reponse:
    resource: "@KarhabtyFutureConducteurBundle/Controller/ReponseController.php"
    type:     annotation

karhabty_future_conducteur_user_reponses:
    resource: "@KarhabtyFutureConducteurBundle/Controller/UserReponsesController.php"
    type:     annotation

karhabty_future_conducteur_question:
    resource: "@KarhabtyFutureConducteurBundle/Controller/QuestionController.php"
    type:     annotation

karhabty_future_conducteur:
    resource: "@KarhabtyFutureConducteurBundle/Resources/config/routing.yml"
    prefix:   /
karhabty_user:
    resource: "@KarhabtyUserBundle/Resources/config/routing.yml"

    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

my_very_secret_route:
    path:     /load
    defaults: { _controller: KarhabtyCalendarBundle:calendar:load}
    options:
        expose: true



count:
    path:     /count
    defaults: { _controller: KarhabtyOffreBundle:Offre:Count}
    options:
        expose: true

Annonce_secret:
    path:     /Aload
    defaults: { _controller: KarhabtyAnnonceBundle:Annonce:recherche}
    options:
        expose: true

annonce_recherche:
    path:     /annonces
    defaults: { _controller: "KarhabtyAnnonceBundle:Annonce:publicannonce" }
    methods:  [GET, POST]



paiement:
    path:     /checkout
    defaults: { _controller: KarhabtyPaiementBundle:Paiement:paiement}
    options:
        expose: true



ajaxDeleteAstuce:
    path:     /deleteAstuceAjax
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:deleteAstuce}
    options:
        expose: true



coupon_generate:
    path:     /generate
    defaults: { _controller: KarhabtyOffreBundle:Coupon:generate}
    options:
        expose: true


