karhabty_astuce:
    resource: "@KarhabtyAstuceBundle/Resources/config/routing.yml"

karhabty_future_conducteur:
    resource: "@KarhabtyFutureConducteurBundle/Resources/config/routing.yml"
    prefix:   /

karhabty_user:
    resource: "@KarhabtyUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

