karhabty_offre_offre:
    resource: "@KarhabtyOffreBundle/Resources/config/routing/offre.yml"
    prefix:   /offre





coupon:
    path:      /coupon/{id}
    defaults: { _controller: "KarhabtyOffreBundle:Coupon:index" }


coupon_generate:
    path:      /generate
    defaults: { _controller: "KarhabtyOffreBundle:Coupon:generate" }



coupon_generate_pdf:
    path:      /coupon_pdf
    defaults: { _controller: "KarhabtyOffreBundle:Coupon:test" }


