offre_afficher:
     path:     /
     defaults: { _controller: "KarhabtyOffreBundle:Offre:getAlloffre" }

offre_index:
    path:     /dashborad_offres
    defaults: { _controller: "KarhabtyOffreBundle:Offre:index" }
    methods:  GET

offre_show:
    path:     /show/{id}
    defaults: { _controller: "KarhabtyOffreBundle:Offre:show" }
    methods:  GET

offre_new:
    path:     /new
    defaults: { _controller: "KarhabtyOffreBundle:Offre:new" }
    methods:  [GET, POST]

offre_edit:
    path:     edit/{id}
    defaults: { _controller: "KarhabtyOffreBundle:Offre:edit" }
    methods:  [GET, POST]

offre_delete:
    path:     delete/{id}
    defaults: { _controller: "KarhabtyOffreBundle:Offre:delete" }
    methods:  DELETE


offre_details:
    path:      /detaille_offre/{id}
    defaults: { _controller: "KarhabtyOffreBundle:Offre:detailOffre" }
    methods:  GET


offres_passes:
    path:      /offres_passes
    defaults: { _controller: "KarhabtyOffreBundle:Offre:OffresPasses" }

offres_trie:
    path:      /trie
    defaults: { _controller: "KarhabtyOffreBundle:Offre:OffresPasses" }

offres_statistique:
    path:      /statistique
    defaults: { _controller: "KarhabtyOffreBundle:Statistique:chart" }

