karhabty_astuce_homepage:
    path:     /
    defaults: { _controller: KarhabtyAstuceBundle:Default:index }



addAstuce:
    path:     /addAstuce
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:addAstuce }

deleteAstuce:
    path:     /deleteAstuce/{id}
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:deleteAstuce}


listAstuce:
    path:     /listAstuce
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:listAstuce}

updateAstuce:
    path:     /updateAstuce/{id}
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:updateAstuce}



infoAstuce:
    path:     /infoAstuce/{id}
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:infoAstuce}
theme:
    path:     /{theme}
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:theme}

addComm:
    path:     /AddComm
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:addComment}