
addAstuce:
    path:     /addAstuce
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:addAstuce }

deleteAstuce:
    path:     /deleteAstuce/{id}
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:deleteAstuce}


listAstuce:
    path:     /listAstuce/{param}
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:listAstuce,'param': 'ALL'}

updateAstuce:
    path:     /updateAstuce/{id}
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:updateAstuce}



infoAstuce:
    path:     /infoAstuce
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:infoAstuce}


test:
    path:     /test/{param}
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:test}

rate:
    path:     /rat
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:rate}



addComm:
    path:     /AddComm
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:addComment}

ajaxDeleteAstuce:
    path:     /deleteAstuceAjax
    defaults: { _controller: KarhabtyAstuceBundle:Astuce:deleteAstuce}
    options:
        expose: true