<?php

namespace Karhabty\FutureConducteurBundle\Repository;

/**
 * UserReponsesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReponsesRepository extends \Doctrine\ORM\EntityRepository
{
}
