event_index:
    path:     /
    defaults: { _controller: "KarhabtyEventsBundle:Event:index" }
    methods:  [GET]
event_filter:
    path:     /filter/{criteria}
    defaults: { _controller: "KarhabtyEventsBundle:Event:index" }
    methods:  [GET]
event_show:
    path:     /show/{id}
    defaults: { _controller: "KarhabtyEventsBundle:Event:show" }
    methods:  [GET]

event_new:
    path:     /new
    defaults: { _controller: "KarhabtyEventsBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /edit/{id}
    defaults: { _controller: "KarhabtyEventsBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /delete/{id}
    defaults: { _controller: "KarhabtyEventsBundle:Event:delete" }
    methods:  DELETE
event_participate:
    path:     /participate/{id}
    defaults: { _controller: "KarhabtyEventsBundle:Event:participate" }
    methods:  [GET]
event_accept:
    path:     /accept/{id}
    defaults: { _controller: "KarhabtyEventsBundle:Event:accept" }
    methods:  [GET]
event_decline:
    path:     /decline/{id}
    defaults: { _controller: "KarhabtyEventsBundle:Event:decline" }
    methods:  [GET]
event_cancel:
    path:     /cancel/{id}
    defaults: { _controller: "KarhabtyEventsBundle:Event:cancel" }
    methods:  [GET]
